### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ozanoner** [wirepas/tutorials#74]
mosquitto.conf links don't work. I believe they should be mosquitto.conf.template
https://github.com/wirepas/tutorials/blob/master/mosquitto/mosquitto.conf.template
here: https://github.com/wirepas/tutorials/tree/master/mosquitto

**Comment by PFigs** [comment]
Hi!

Could you elaborate more on the issue you are seeing? 

The template is used within the docker entrypoint to generate/populate a mosquito.conf (within the container).

**Comment by ozanoner** [comment]
not something very important. Just see the attached image. Those links cause 404 error
![image](https://user-images.githubusercontent.com/6412075/70330478-8e6c0a80-1835-11ea-907c-0d3c280105f7.png)

**Comment by PFigs** [comment]
Hi,

Great I understand now the issue! We will review the urls and update the broken ones.

Thanks for your help!
